name: Java CI with Gradle

on:
  push:
    branches: [ "action" ]
  pull_request:
    branches: [ "action" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
        gradle-version: '8.5'

    - name: Build with Gradle
      run: gradle build

    - run: java -jar build/libs/CryptoNetPol.jar
    - run: ls
    - run: ls build
    - run: ls build/libs
